version: '3'
services:
  server:
    build: 
      dockerfile: cmd/server/Dockerfile
      context: ./
    ports:
     - "8080:8080"
  client:
    build:
      dockerfile: cmd/client/Dockerfile
      context: ./

networks:
  default:
    external: true
